import 'package:mini_ui_project/core/models/profile_model/profile_information.dart';


List<PersonProfile> systemUsers = [
    PersonProfile(
    image: "assets/images/person.jpg",
    name: "admin",
    phoneNumber: "0952139761",
    password: "12345678", 
    countryCode: "SY",
    numberOfBeans: 230,
  ),
  PersonProfile(
    image: "assets/images/person.jpg",
    name: "Emma Johnson",
    phoneNumber: "944123456",
    password: "Emma@123", 
    countryCode: "US",
    numberOfBeans: 120,
  ),
  PersonProfile(
    image: "assets/images/person.jpg",
    name: "Liam Smith",
    phoneNumber: "771234567",
    password: "Liam@456",
    countryCode: "SY",
    numberOfBeans: 85,
  ),
  PersonProfile(
    image: "assets/images/person.jpg",
    name: "Olivia Brown",
    phoneNumber: "501234567",
    password: "Olivia@789",
    countryCode: "DE",
    numberOfBeans: 230,
  ),
  PersonProfile(
    image: "assets/images/person.jpg",
    name: "Noah Wilson",
    phoneNumber: "612345678",
    password: "Noah@321",
    countryCode: "FR",
    numberOfBeans: 175,
  ),
  PersonProfile(
    image: "assets/images/person.jpg",
    name: "Sophia Davis",
    phoneNumber: "723456789",
    password: "Sophia@654",
    countryCode: "GB",
    numberOfBeans: 95,
  ),
  PersonProfile(
    image: "assets/images/person.jpg",
    name: "James Miller",
    phoneNumber: "812345678",
    password: "James@987",
    countryCode: "CA",
    numberOfBeans: 310,
  ),
  PersonProfile(
    image: "assets/images/person.jpg",
    name: "Mia Anderson",
    phoneNumber: "934567890",
    password: "Mia@111",
    countryCode: "AE",
    numberOfBeans: 145,
  ),
  PersonProfile(
    image: "assets/images/person.jpg",
    name: "Lucas Thomas",
    phoneNumber: "665432198",
    password: "Lucas@222",
    countryCode: "NL",
    numberOfBeans: 260,
  ),
  PersonProfile(
    image: "assets/images/person.jpg",
    name: "Charlotte White",
    phoneNumber: "734561289",
    password: "Charlotte@333",
    countryCode: "TR",
    numberOfBeans: 190,
  ),
  PersonProfile(
    image: "assets/images/person.jpg",
    name: "Benjamin Harris",
    phoneNumber: "912345123",
    password: "Benjamin@444",
    countryCode: "SA",
    numberOfBeans: 405,
  ),
];